import JSZip from 'jszip'
import { describe, expect, it, vi } from 'vitest'
import { GROUPS, canvasLinkedAssetIds, createSeedProject, isLegacyBaliSeed, makeSection, normalizeLayoutBoxes, normalizeProject, normalizeReferenceMediaSlots, referenceMediaSlot, timelineDayStartsAfterItemRemoval } from './catalog'
import { runQa } from './qa'
import { assetsManifestJson, canvasDocumentJson, exportZip, manifestJson, manifestYaml, projectLoadJson, standaloneHtml } from './exporters'
import { CURRENT_CATALOG_VERSION, CURRENT_SCHEMA_VERSION, isDirectProjectPayload, migrateProject } from './migrations'
import { buildSplitPlan } from './image-split'
import { createCustomLayout, layoutPresetsFor, normalizeCustomLayout, patchLayoutItem, swapCustomLayoutPlacements } from './image-layout'
import { isRichTextEmpty, richTextToPlainText, sanitizeRichText } from './rich-text'
import { moveSectionUnit, normalizeContentGroups, removeSectionsFromGroups } from './content-groups'
import { joinPair, joinTimeline, splitPair, splitTimeline } from './preset-item-format'

describe('delivery QA', () => {
  it('starts with a blank project and shared placeholder copy', () => { const project = createSeedProject(); expect(project.name).toBe('새 내일스패셜 기획안'); expect(project.sections).toEqual([]); expect(project.assets).toEqual([]); expect(project.page.title).toBe(''); expect(makeSection('image').mediaLayout).toBe('auto'); expect(makeSection('list').items).toHaveLength(3); expect(makeSection('table').tableHeaders).toEqual(['구분', '내용']); expect(makeSection('icon-card').iconCards).toHaveLength(3); expect(makeSection('menu-zigzag').items[0]).toContain('|'); expect(makeSection('timeline')).toMatchObject({ eyebrow: 'Category Label', title: '제목', body: '본문' }); expect(makeSection('text')).toMatchObject({ eyebrow: 'Category Label', title: '제목', body: '본문', items: [] }) })
  it('collapses rich-text fields that contain formatting without visible copy', () => { expect(isRichTextEmpty('')).toBe(true); expect(isRichTextEmpty('<br>')).toBe(true); expect(isRichTextEmpty('<strong></strong><span style="color:#07858b">&nbsp;</span>')).toBe(true); expect(isRichTextEmpty('<strong>제목</strong>')).toBe(false) })
  it('uses readable copy instead of HTML markup in layer labels', () => { expect(richTextToPlainText('<span style="font-size: 1.32em; color: #07858b">우리만 <strong>여행</strong></span><br>안내')).toBe('우리만 여행 안내') })
  it('keeps Enter line breaks in common rich-text fields and exports', () => { const project = createSeedProject(); const section = makeSection('text'); section.body = '첫째 줄\n둘째 줄'; project.sections = [section]; expect(sanitizeRichText('<div>첫째 줄</div><div>둘째 줄</div>')).toBe('첫째 줄<br>둘째 줄'); expect(sanitizeRichText(section.body)).toBe('첫째 줄<br>둘째 줄'); expect(standaloneHtml(project)).toContain('첫째 줄<br>둘째 줄') })
  it('renders text flow blocks in preview order instead of legacy absolute coordinates', () => { const project = createSeedProject(); const section = makeSection('text'); section.title = '첫 번째 제목'; section.layoutBoxes = [...normalizeLayoutBoxes(section), { id: 'extra', kind: 'text', column: 1, row: 30, columnSpan: 12, rowSpan: 3, zIndex: 3, eyebrow: '', title: '두 번째 제목', text: '설명' }]; project.sections = [section]; const html = standaloneHtml(project); expect(html).toContain('text-flow-block'); expect(html).toContain('text-flow-card .section-text-content h2{max-width:590px;margin:0 0 16px;font-size:31px;line-height:1.35}'); expect(html).not.toContain('height:1914px'); expect(html.indexOf('첫 번째 제목')).toBeLessThan(html.indexOf('두 번째 제목')) })
  it('keeps Korean word spacing and repeated spaces in common rich-text fields', () => { expect(sanitizeRichText('내일 스패셜 메이킹 스튜디오')).toBe('내일 스패셜 메이킹 스튜디오'); expect(sanitizeRichText('첫째  둘째')).toBe('첫째  둘째') })
  it('keeps a just-typed trailing space in all separator-based preset item fields', () => { const pair = joinPair('제목', '이미지 설명 뒤 공백 '); expect(splitPair(pair)).toEqual({ title: '제목', body: '이미지 설명 뒤 공백 ' }); const timelineValue = joinTimeline('00:00', '새 일정', '정갈하게 차려진 베트남 가정식으로 '); expect(splitTimeline(timelineValue)).toEqual({ time: '00:00', title: '새 일정', body: '정갈하게 차려진 베트남 가정식으로 ' }); const project = createSeedProject(); const timeline = makeSection('timeline'); timeline.items = [timelineValue]; project.sections = [timeline]; expect(standaloneHtml(project)).toContain('정갈하게 차려진 베트남 가정식으로 ') })
  it('offers the place comparison image preset but not the deprecated offer preset', () => { const types = GROUPS.flatMap(group => group.types); expect(types).toContain('caption-grid'); expect(types).not.toContain('offer') })
  it('keeps only consecutive editor content groups and preserves them in load JSON', () => { const project = createSeedProject(); const first = makeSection('image'); const second = makeSection('image'); const third = makeSection('image'); project.sections = [first, second, third]; const groups = normalizeContentGroups([{ id: 'rooms', name: '객실 소개', sectionIds: [first.id, second.id], collapsed: true }, { id: 'invalid', name: '건너뜀', sectionIds: [first.id, third.id] }], project.sections); expect(groups).toEqual([{ id: 'rooms', name: '객실 소개', sectionIds: [first.id, second.id], collapsed: true }]); expect(removeSectionsFromGroups(groups, [first.id], project.sections)).toEqual([]); project.contentGroups = groups; expect(JSON.parse(projectLoadJson(project)).contentGroups).toEqual(groups) })
  it('moves blocks and groups across a content group without inserting inside it', () => { const first = makeSection('text'); const groupedFirst = makeSection('image'); const groupedSecond = makeSection('list'); const last = makeSection('icon-card'); const sections = [first, groupedFirst, groupedSecond, last]; const groups = [{ id: 'package', name: '패키지 구성', sectionIds: [groupedFirst.id, groupedSecond.id], collapsed: false }]; const movedDown = moveSectionUnit(sections, groups, first.id, 1); expect(movedDown.map(section => section.id)).toEqual([groupedFirst.id, groupedSecond.id, first.id, last.id]); expect(normalizeContentGroups(groups, movedDown)).toHaveLength(1); const movedUp = moveSectionUnit(sections, groups, last.id, -1); expect(movedUp.map(section => section.id)).toEqual([first.id, last.id, groupedFirst.id, groupedSecond.id]); expect(normalizeContentGroups(groups, movedUp)).toHaveLength(1); const groupMoved = moveSectionUnit(sections, groups, groupedSecond.id, -1); expect(groupMoved.map(section => section.id)).toEqual([groupedFirst.id, groupedSecond.id, first.id, last.id]); expect(normalizeContentGroups(groups, groupMoved)).toHaveLength(1) })
  it('keeps reference-layout image slots aligned with their cards', () => {
    expect(normalizeReferenceMediaSlots('caption-grid', ['왼쪽', '오른쪽'], ['left', 'unused', 'right'])).toEqual(['left', 'right'])
    expect(normalizeReferenceMediaSlots('caption-grid', ['왼쪽', '오른쪽', '세 번째'], ['left', 'right', 'third'])).toEqual(['left', 'right', 'third'])
    expect(normalizeReferenceMediaSlots('menu-zigzag', ['a', 'b'], ['menu-a'])).toEqual(['menu-a', ''])
    expect(normalizeReferenceMediaSlots('timeline', ['a', 'b'], ['hero', 'first'])).toEqual(['hero', 'first', ''])
    expect(referenceMediaSlot('menu-zigzag', 1)).toBe(1)
    expect(referenceMediaSlot('timeline', 0)).toBe(1)
  })
  it('keeps every image linked by a canvas block during library cleanup', () => { const standard = makeSection('image'); standard.layoutBoxes = normalizeLayoutBoxes(standard).map(box => box.kind === 'media' ? { ...box, assetIds: ['standard'] } : box); standard.mediaIds = ['legacy']; const reference = makeSection('caption-grid'); reference.mediaIds = ['reference', '']; expect(canvasLinkedAssetIds([standard, reference]).sort()).toEqual(['legacy', 'reference', 'standard']) })
  it('keeps detailed-schedule day labels aligned after removing an individual schedule item', () => {
    expect(timelineDayStartsAfterItemRemoval([0, 2], 3, 1)).toEqual([0, 1])
    expect(timelineDayStartsAfterItemRemoval([0, 2], 3, 2)).toEqual([0])
    expect(timelineDayStartsAfterItemRemoval([0, 2], 4, 2)).toEqual([0, 2])
  })
  it('migrates legacy named blocks into shared structures', () => { const project = createSeedProject(); project.sections = [{ ...makeSection('text'), type: 'hotel-showcase' as never }, { ...makeSection('text'), type: 'faq' as never }, { ...makeSection('text'), type: 'offer-price' as never }]; expect(normalizeProject(project).sections.map(section => section.type)).toEqual(['image', 'list', 'offer']) })
  it('plans image splits without losing edge pixels', () => { expect(buildSplitPlan(101, 99, 'grid-4')).toEqual([{ x: 0, y: 0, width: 50, height: 49, index: 1 }, { x: 50, y: 0, width: 51, height: 49, index: 2 }, { x: 0, y: 49, width: 50, height: 50, index: 3 }, { x: 50, y: 49, width: 51, height: 50, index: 4 }]) })
  it('creates and bounds a user-defined image layout', () => { const initial = createCustomLayout(['one', 'two', 'three']); expect(initial[0]).toMatchObject({ assetId: 'one', columnSpan: 7, rowSpan: 4 }); const edited = patchLayoutItem(initial, 'one', { column: 99, columnSpan: 12, row: -1, rowSpan: 9 }); expect(edited[0]).toMatchObject({ column: 1, row: 1, columnSpan: 12, rowSpan: 6 }); expect(normalizeCustomLayout(['one', 'four'], edited).map(item => item.assetId)).toEqual(['one', 'four']) })
  it('swaps custom-image placements with their displayed image order', () => { const initial = createCustomLayout(['one', 'two', 'three']); const swapped = swapCustomLayoutPlacements(initial, 'two', 'three'); expect(swapped.find(item => item.assetId === 'two')).toMatchObject({ column: 8, row: 3, columnSpan: 5, rowSpan: 2 }); expect(swapped.find(item => item.assetId === 'three')).toMatchObject({ column: 8, row: 1, columnSpan: 5, rowSpan: 2 }) })
  it('offers the same three layout choices for every three-or-more image mix', () => { expect(layoutPresetsFor(['one', 'two'], { one: 'portrait', two: 'landscape' })).toEqual([]); const portraitMix = layoutPresetsFor(['p', 'l1', 'l2'], { p: 'portrait', l1: 'landscape', l2: 'landscape' }); const landscapeMix = layoutPresetsFor(['l1', 'l2', 'l3'], { l1: 'landscape', l2: 'landscape', l3: 'landscape' }); expect(portraitMix.map(preset => preset.label)).toEqual(['상단 와이드', '세로 강조 왼쪽', '세로 강조 오른쪽']); expect(landscapeMix.map(preset => preset.label)).toEqual(portraitMix.map(preset => preset.label)); expect(portraitMix[1].items[0]).toMatchObject({ columnSpan: 7, rowSpan: 4 }) })
  it('recognizes only the untouched legacy Bali seed', () => { const project = createSeedProject(); const titles = ['시간이 천천히 흐르는\n발리의 프라이빗 휴식', '내일투어가 고른 세 가지 이유', '숲과 바다가 만나는 프라이빗 풀빌라', '내일투어 단독 혜택', '여행 전 자주 묻는 질문']; Object.assign(project, { name: '발리 프라이빗 리조트 기획안', page: { title: '발리, 둘만의 속도로', subtitle: '프라이빗 풀빌라 5일', destination: '인도네시아 · 발리', internalMemo: '' }, sections: titles.map(title => ({ ...makeSection('text'), title })) }); expect(isLegacyBaliSeed(project)).toBe(true); project.sections.push(makeSection('text')); expect(isLegacyBaliSeed(project)).toBe(false) })
  it('blocks web captures', () => { const project = createSeedProject(); project.assets.push({ id:'a', name:'capture.png', src:'', provider:'web-capture', sourceId:'', assetStage:'reference', usageScope:'hero', rightsStatus:'prohibited', qualityGrade:'C', approval:'rejected', evidence:'', alt:'' }); expect(runQa(project).filter(i => i.level === 'error').length).toBeGreaterThan(0) })
  it('requires images in final image blocks', () => { const project = createSeedProject(); project.sections = [makeSection('image')]; project.deliveryStage = 'customer-final'; expect(runQa(project).some(i => i.id.startsWith('media-required-'))).toBe(true) })
  it('exports reference layout block contracts', () => { const project = createSeedProject(); const place = makeSection('caption-grid'); place.items = [joinPair('원더파크', '대표 관광지와 함께 둘러보는 장소'), joinPair('호이안 올드타운', '여유롭게 산책하기 좋은 거리'), joinPair('세 번째 장소', '추가 카드 설명')]; project.sections = [place, makeSection('menu-zigzag'), makeSection('timeline')]; const html = standaloneHtml(project); expect(html).toContain('caption-grid-block'); expect(html).not.toContain('caption-grid-pair'); expect(html).toContain('원더파크'); expect(html).toContain('대표 관광지와 함께 둘러보는 장소'); expect(html).toContain('호이안 올드타운'); expect(html).toContain('세 번째 장소'); expect(html.match(/<figure>/g)).toHaveLength(3); expect(html).toContain('menu-zigzag-block'); expect(html).toContain('timeline-block'); expect(JSON.parse(manifestJson(project)).sections.map((section: { type: string }) => section.type)).toEqual(['caption-grid', 'menu-zigzag', 'timeline']) })
  it('matches the canvas list and detailed timeline styling in the full-page preview', () => { const project = createSeedProject(); const list = makeSection('list'); list.listStyle = 'offer'; list.items = ['제목 줄\n본문 줄']; const timeline = makeSection('timeline'); project.sections = [list, timeline]; const html = standaloneHtml(project); expect(html).toContain('preview-list preview-list-offer'); expect(html).toContain('preview-list-offer>div{border:0;border-radius:30px;background:#07979c'); expect(html).toContain('.preview-list>div>span{white-space:pre-wrap}'); expect(html).toContain('제목 줄\n본문 줄'); expect(html).toContain('.timeline-reference-body{padding:45px 10px 54px;background:#fff;text-align:center}') })
  it('uses the standard copy header before menu and timeline reference layouts', () => { const project = createSeedProject(); const menu = makeSection('menu-zigzag'); const timeline = makeSection('timeline'); Object.assign(menu, { eyebrow: 'MENU LABEL', title: '메뉴 제목', body: '메뉴 본문' }); Object.assign(timeline, { eyebrow: 'TIMELINE LABEL', title: '일정 제목', body: '일정 본문' }); project.sections = [menu, timeline]; const html = standaloneHtml(project); const menuStart = html.indexOf('class="block special-section menu-zigzag-block"'); const timelineStart = html.indexOf('class="block special-section timeline-block"'); expect(html).toContain('special-common-copy'); expect(html).toContain('fonts.googleapis.com/css2?family=Noto+Sans+KR'); expect(html).toContain('font-size:31px;line-height:1.35;font-weight:600'); expect(html.indexOf('MENU LABEL', menuStart)).toBeLessThan(html.indexOf('<div class="menu-zigzag">', menuStart)); expect(html.indexOf('TIMELINE LABEL', timelineStart)).toBeLessThan(html.indexOf('<div class="timeline-reference-body">', timelineStart)) })
  it('keeps image-description cards inside the 720px preview canvas', () => { const project = createSeedProject(); project.sections = [makeSection('menu-zigzag')]; const html = standaloneHtml(project); expect(html).toContain('<style>.menu-zigzag{margin:0;padding:0 18px 42px}</style>'); expect(html).not.toContain('<main class="page"><style>') })
  it('exports the current YAML and JSON contract version', () => { const project = createSeedProject(); expect(project.schemaVersion).toBe(CURRENT_SCHEMA_VERSION); expect(manifestYaml(project)).toContain(`schema_version: ${CURRENT_SCHEMA_VERSION}`); expect(JSON.parse(manifestJson(project)).delivery_stage).toBe('internal-draft') })
  it('migrates unversioned and 2.0 load projects without mutating the backup', () => { const current = createSeedProject(); const legacy = JSON.parse(JSON.stringify({ ...current, schemaVersion: '2.0', catalogVersion: undefined, futureRoot: { keep: true } })); const result = migrateProject(legacy); expect(result.migrated).toBe(true); expect(result.project.schemaVersion).toBe(CURRENT_SCHEMA_VERSION); expect(result.project.catalogVersion).toBe(CURRENT_CATALOG_VERSION); expect(result.project.migrationLog?.[0]?.from).toBe('2.0'); expect((result.project as unknown as { futureRoot: { keep: boolean } }).futureRoot.keep).toBe(true); expect((result.backup as { schemaVersion: string }).schemaVersion).toBe('2.0'); expect(isDirectProjectPayload({ ...legacy, schemaVersion: undefined })).toBe(true) })
  it('keeps the selected text and image placement in the project and exports', () => { const project = createSeedProject(); const section = makeSection('text'); section.contentLayout = 'media-left'; project.sections = [section]; expect(normalizeProject(project).sections[0].contentLayout).toBe('media-left'); expect(JSON.parse(manifestJson(project)).sections[0].content_layout).toBe('media-left'); expect(JSON.parse(canvasDocumentJson(project)).blocks[0].bindings.content_layout).toBe('media-left'); expect(standaloneHtml(project)).toContain('content-layout-media-left') })
  it('creates editable grid boxes for legacy sections and preserves added boxes', () => { const section = makeSection('image'); section.layoutBoxes = []; const migrated = normalizeProject({ ...createSeedProject(), sections: [section] }).sections[0]; expect(normalizeLayoutBoxes(migrated).map(box => box.id)).toEqual(['content', 'media']); migrated.layoutBoxes = [...normalizeLayoutBoxes(migrated), { id: 'extra', kind: 'text', column: 2, row: 12, columnSpan: 5, rowSpan: 3, zIndex: 4, text: '추가 문구' }]; const boxes = normalizeLayoutBoxes(migrated); expect(boxes.find(box => box.id === 'extra')).toMatchObject({ kind: 'text', column: 2, text: '추가 문구' }); expect(JSON.parse(manifestJson({ ...createSeedProject(), sections: [migrated] })).sections[0].layout_boxes).toHaveLength(3) })
  it('does not restore a deleted base image card after layout normalization or reload', () => { const section = makeSection('image'); section.removedLayoutBoxIds = ['media']; expect(normalizeLayoutBoxes(section).map(box => box.id)).toEqual(['content']); const reloaded = normalizeProject({ ...createSeedProject(), sections: [section] }).sections[0]; expect(normalizeLayoutBoxes(reloaded).map(box => box.id)).toEqual(['content']); expect(reloaded.removedLayoutBoxIds).toEqual(['media']) })
  it('exports image blocks as an ordered text and image flow', () => { const project = createSeedProject(); const section = makeSection('image'); section.layoutBoxes = [...normalizeLayoutBoxes(section), { id: 'after-photo', kind: 'text', column: 1, row: 13, columnSpan: 12, rowSpan: 4, zIndex: 3, eyebrow: 'DETAIL', title: '이미지 아래 설명', text: '사진 다음에 이어지는 설명입니다.' }]; project.sections = [section]; const html = standaloneHtml(project); expect(html).toContain('image-flow-block'); expect(html.indexOf('Category Label')).toBeLessThan(html.indexOf('이미지 아래 설명')); expect(html).toContain('사진 다음에 이어지는 설명입니다.') })
  it('exports directly edited image positions with the same custom grid spans', () => {
    const project = createSeedProject(); const section = makeSection('image'); const ids = ['wide', 'top', 'bottom']
    project.assets = ids.map(id => ({ id, name: `${id}.jpg`, src: `data:image/jpeg;base64,${id}`, provider: 'provided' as const, sourceId: '', assetStage: 'original' as const, usageScope: 'gallery' as const, rightsStatus: 'cleared' as const, qualityGrade: 'A' as const, approval: 'approved' as const, evidence: '', alt: id }))
    section.mediaIds = ids; section.layoutBoxes = normalizeLayoutBoxes(section).map(box => box.id === 'media' ? { ...box, assetIds: ids } : box)
    section.mediaLayout = 'custom'; section.mediaLayoutItems = [
      { assetId: 'wide', column: 1, row: 1, columnSpan: 7, rowSpan: 4, focus: 'left center' },
      { assetId: 'top', column: 8, row: 1, columnSpan: 5, rowSpan: 2, focus: 'center top' },
      { assetId: 'bottom', column: 8, row: 3, columnSpan: 5, rowSpan: 2, focus: 'right bottom' },
    ]
    project.sections = [section]
    const html = standaloneHtml(project)
    expect(html).toContain('display:grid;gap:5px;grid-template-columns:repeat(12,minmax(0,1fr));grid-template-rows:repeat(4,108px)')
    expect(html).toContain('grid-column:1 / span 7;grid-row:1 / span 4')
    expect(html).toContain('grid-column:8 / span 5;grid-row:3 / span 2')
    expect(html).toContain('object-position:right bottom')
  })
  it('exports a single fixed PC canvas contract', () => { const project = createSeedProject(); const canvas = JSON.parse(canvasDocumentJson(project)); const html = standaloneHtml(project); expect(canvas.canvas.base_width).toBe(720); expect(canvas.canvas.preview_viewports).toEqual([720]); expect(canvas.blocks.every((block: Record<string, unknown>) => !('mobile_behavior' in block))).toBe(true); expect(html).toContain('width=720'); expect(html).toContain('min-width:720px'); expect(html).not.toContain('max-width:100%'); expect(html).not.toContain('@media(max-width'); expect(assetsManifestJson(project)).toContain('"assets": []') })
  it('keeps icon cards in the editable and exported document contracts', () => { const project = createSeedProject(); const section = makeSection('icon-card'); project.sections = [section]; const html = standaloneHtml(project); expect(JSON.parse(manifestJson(project)).sections[0].icon_cards).toHaveLength(3); expect(JSON.parse(canvasDocumentJson(project)).blocks[0].content.icon_cards[0].icon).toBe('calendar'); expect(html).toContain('icon-cards'); expect(html).toContain(`<section id="${section.id}" class="block content-layout-text-top"><div class="block-copy">`); expect(html).not.toContain(`<section id="${section.id}" class="block content-layout-text-top"><div class="block-canvas"`) })
  it('does not block a final page on removed sales data', () => { const project = createSeedProject(); project.page.title = '테스트'; project.sections = [makeSection('text')]; project.deliveryStage = 'customer-final'; expect(runQa(project).map(item => item.id)).not.toEqual(expect.arrayContaining(['canonical-mismatch', 'price-order', 'source-verify', 'primary-cta'])) })
  it('embeds connected images without campaign data in standalone HTML', () => { const project = createSeedProject(); const id = crypto.randomUUID(); const hero = makeSection('image'); project.sections = [hero]; project.assets.push({ id, name:'hero.png', src:'data:image/png;base64,AA==', provider:'provided', sourceId:'', assetStage:'original', usageScope:'hero', rightsStatus:'cleared', qualityGrade:'A', approval:'approved', evidence:'provided', alt:'대표 이미지' }); project.sections[0].mediaIds = [id]; const html = standaloneHtml(project); expect(html).toContain('data:image/png;base64,AA=='); expect(html).not.toContain('campaign-data'); expect(html).toContain('대표 이미지') })
  it('keeps image download status in the manifest and reload JSON', () => { const project = createSeedProject(); project.assets.push({ id:'downloaded-image', name:'hotel.jpg', src:'https://example.com/hotel.jpg', provider:'provided', sourceId:'', assetStage:'reference', usageScope:'hero', rightsStatus:'unknown', qualityGrade:'B', approval:'pending', evidence:'', alt:'호텔', download:{ status:'pending', source:'https://example.com/hotel.jpg' } }); expect(JSON.parse(manifestJson(project)).media[0].download.status).toBe('pending'); expect(JSON.parse(projectLoadJson(project)).assets[0].download.source).toBe('https://example.com/hotel.jpg') })
  it('records URL image download failures inside the designer handoff ZIP', async () => {
    const project = createSeedProject()
    const image = { id:'broken-image', name:'broken-image.jpg', src:'https://example.com/restricted-image.jpg', provider:'provided' as const, sourceId:'', assetStage:'reference' as const, usageScope:'hero' as const, rightsStatus:'unknown' as const, qualityGrade:'B' as const, approval:'pending' as const, evidence:'', alt:'접근 제한 이미지' }
    project.assets.push(image)
    let archive: Blob | MediaSource | undefined
    const createObjectUrl = vi.spyOn(URL, 'createObjectURL').mockImplementation(blob => { archive = blob; return 'blob:handoff' })
    const revokeObjectUrl = vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined)
    vi.stubGlobal('window', {})
    vi.stubGlobal('fetch', vi.fn(async () => { throw new Error('CORS blocked') }))
    vi.stubGlobal('document', { createElement: vi.fn(() => ({ click: vi.fn(), href: '', download: '' })) })
    try {
      const failures = await exportZip(project)
      expect(failures.join('\n')).toContain('CORS blocked')
      if (!(archive instanceof Blob)) throw new Error('ZIP 다운로드 Blob이 생성되지 않았습니다.')
      const zip = await JSZip.loadAsync(await archive.arrayBuffer())
      const result = JSON.parse(await zip.file('이미지-패키징-결과.json')!.async('text'))
      expect(result[0]).toMatchObject({ id: image.id, status: 'failed', source: image.src, failureReason: 'CORS blocked' })
      expect(await zip.file(`assets/${image.id}.url.txt`)!.async('text')).toBe(`${image.src}\n`)
      expect(await zip.file('index.html')!.async('text')).toContain('<main class="page"></main>')
      expect(await zip.file('이미지-다운로드-확인필요.md')!.async('text')).toContain('CORS blocked')
    } finally {
      vi.unstubAllGlobals()
      createObjectUrl.mockRestore()
      revokeObjectUrl.mockRestore()
    }
  })
})
